# Generated by Django 3.1.8 on 2021-07-07 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_admin_photo', models.ImageField(blank=True, null=True, upload_to='company_admin_photos/', verbose_name="Company's admin photo(optional)")),
                ('company_admin_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name="Company's admin mobile number")),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyadminprofile', to=settings.AUTH_USER_MODEL, verbose_name='Company admin')),
            ],
            options={
                'verbose_name': 'CompanyAdminProfile',
                'verbose_name_plural': 'CompanyAdminProfiles',
            },
        ),
        migrations.CreateModel(
            name='ParkAdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_admin_photo', models.ImageField(blank=True, null=True, upload_to='park_admin_photos/', verbose_name="park's admin photo(optional)")),
                ('park_admin_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name="park's admin mobile number")),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parkadminprofile', to=settings.AUTH_USER_MODEL, verbose_name='Park admin')),
                ('company_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkadminprofilecompanyadmin', to='account.companyadminprofile', verbose_name="Park admin's company admin")),
            ],
            options={
                'verbose_name': 'ParkAdminProfile',
                'verbose_name_plural': 'ParkAdminProfiles',
            },
        ),
    ]
