# Generated by Django 3.1.8 on 2021-08-08 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile number')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile number')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_park', to='park.park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
