# Generated by Django 3.1.8 on 2021-08-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park'),
        ),
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
