# Generated by Django 3.1.8 on 2021-08-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210808_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='mobile_number',
        ),
    ]
