# Generated by Django 3.1.8 on 2021-07-07 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.BooleanField(default=False, verbose_name='verification')),
                ('company_logo', models.ImageField(upload_to='company_logos/', verbose_name="Company's logo")),
                ('company_name', models.CharField(max_length=255, verbose_name="Company's name")),
                ('company_email', models.EmailField(max_length=255, verbose_name="Company's email")),
                ('company_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name="Company's mobile number")),
                ('company_about', models.TextField(max_length=500, verbose_name='About Company')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='account.companyadminprofile', verbose_name="Company's admin")),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
