# Generated by Django 3.1.8 on 2021-07-07 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=255, verbose_name="Park's name")),
                ('park_email', models.EmailField(max_length=255, verbose_name="Park's email")),
                ('total_parking_space', models.PositiveIntegerField(verbose_name='Total parking space')),
                ('occupied_space', models.PositiveIntegerField(verbose_name='Occupied space')),
                ('park_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid mobile number!', regex='^\\+?1?\\d{9,15}$')], verbose_name="Park's mobile number")),
                ('park_address', models.CharField(max_length=255, verbose_name="Park's address")),
                ('park_coordinates', models.CharField(max_length=255, verbose_name="Park's Coordinates")),
                ('park_about', models.TextField(max_length=500, verbose_name='About Park')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parkadmin', to='account.parkadminprofile', verbose_name="Park's admin")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='company.company', verbose_name="Park's company")),
            ],
            options={
                'verbose_name': 'Park',
                'verbose_name_plural': 'Parks',
            },
        ),
        migrations.CreateModel(
            name='ParkOtherService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_service', models.CharField(max_length=255, verbose_name="Park's other service(Optional)")),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'ParkOtherService',
                'verbose_name_plural': 'ParkOtherServices',
            },
        ),
        migrations.CreateModel(
            name='ParkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_images', models.FileField(upload_to='park_images/', verbose_name="Park's images(optional)")),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'ParkImage',
                'verbose_name_plural': 'ParkImages',
            },
        ),
    ]
