# Generated by Django 3.1.8 on 2021-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_auto_20210726_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='park_closing_time',
            field=models.CharField(choices=[('1am', '1am'), ('2am', '2am'), ('3am', '3am'), ('4am', '4am'), ('5am', '5am'), ('6am', '6am'), ('7am', '7am'), ('8am', '8am'), ('9am', '9am'), ('10am', '10am'), ('11am', '11am'), ('12am', '12am'), ('1pm', '1pm'), ('2pm', '2pm'), ('3pm', '3pm'), ('4pm', '4pm'), ('5pm', '5pm'), ('6pm', '6pm'), ('7pm', '7pm'), ('8pm', '8pm'), ('9pm', '9pm'), ('10pm', '10pm'), ('11pm', '11pm'), ('12pm', '12pm')], max_length=255, verbose_name="Park's closing time"),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_coordinates',
            field=models.CharField(max_length=255, verbose_name="Park's Coordinates"),
        ),
    ]
