# Generated by Django 3.1.8 on 2021-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20210726_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='park_coordinates',
        ),
        migrations.AddField(
            model_name='park',
            name='park_lat',
            field=models.CharField(default=12.45360086805246, max_length=255, verbose_name="Park's latitude"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='park_lon',
            field=models.CharField(default=9.243660194179522, max_length=255, verbose_name="Park's longitude"),
            preserve_default=False,
        ),
    ]
