# Generated by Django 3.1.8 on 2021-07-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('park', '0005_auto_20210728_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park', to='company.company'),
        ),
    ]
