# Generated by Django 3.1.8 on 2021-08-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_auto_20210728_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='occupied_space',
        ),
    ]
